$(function(){
	$('#one>table>tbody').load('../php/manager.php',function(){	
		$('.sc').click(function(){
			$.post('../php/u_del.php',{no:$(this).parent().siblings('.no').html()},function(data){
				if(data=="1"){
					alert('删除成功');
					location.reload();
				}
			});
		});
		$('.xg').click(function(){
			$('[name="form2"]').show();
			$('[name="form1"]').hide();
			$('[name="form"]').hide();
			$.post('../php/u_sel1.php',{'uid':$(this).parent().siblings('.no').html()},function(data){
				$('[name="uname2"]').val(data.name);
				$('[name="pwd2"]').val(data.pwd);
				var no=data.dno;		
				$('[name="btn2"]').click(function(){
					$.post('../php/u_upd.php',{uid:no,
						uname:$('[name="uname2"]').val(),pwd:$('[name="pwd2"]').val()},function(data){
						alert(data);
						location.reload();
					});
				});
			});
		});		
	});
	$('#two>table>tbody').load('../php/manager1.php',function(){
		$('.g_sc').click(function(){
			$.post('../php/g_del.php',{no:$(this).parent().siblings('.g_no').html()},function(data){
				if(data=="1"){
					alert('删除成功');
					location.reload();
				}
			});
		});
		$('.g_xg').click(function(){
			$('[name="g_form2"]').show();
			$('[name="g_form1"]').hide();
			$('[name="g_form"]').hide();
			$.post('../php/g_sel1.php',{'uid':$(this).parent().siblings('.g_no').html()},function(data){
				$('[name="g_uname2"]').val(data.name);
				$('[name="g_price2"]').val(data.price);
				$('[name="g_img2"]').val(data.img);
				var no=data.dno;		
				$('[name="g_btn2"]').click(function(){
					$.post('../php/g_upd.php',{uid:no,
						uname:$('[name="g_uname2"]').val(),price:$('[name="g_price2"]').val(),
						img:$('[name="g_img2"]').val()},function(data){
						alert(data);
						location.reload();
					});
				});
			});
		});		
	});
	$('#three>table>tbody').load('../php/manager2.php',function(){
		$('.s_sc').click(function(){
			$.post('../php/s_del.php',{name:$(this).parent().prev().html()},function(data){
				if(data=="1"){
					alert('删除成功');
					location.reload();
				}
			});
		});

	});
	$('#section>.left>.all>li').click(function(){
		var tag=$(this).attr('data-s');
		var now=$('#section>.right>.open');
		now.css('display','none');
		now.removeClass('open');
		$(tag).css('display','block');
		$(tag).addClass('open');
	});

	$('#add_u').click(function(){
			$('[name="form"]').toggle();
			$('[name="form1"]').hide();
			$('[name="form2"]').hide();
			$('[name="btn"]').click(function(){
			var result=$('[name="form"]').serialize();
			$.post('../php/u_add.php',result,function(data){
				if(data=="exit"){
					alert('添加成功');
					location.reload();
				};
				})
			});
		});
	$('#select_u').click(function(){
			$('[name="form1"]').toggle();
			$('[name="form"]').hide();
			$('[name="form2"]').hide();
			$('[name="btn1"]').click(function(){
			var result=$('[name="form1"]').serialize();
			$.post('../php/u_sel.php',result,function(data){
					alert(data);
			});
		});
		});
    $('#add_g').click(function(){
			$('[name="g_form"]').toggle();
			$('[name="g_form1"]').hide();
			$('[name="g_form2"]').hide();
			$('[name="g_btn"]').click(function(){
			var result=$('[name="g_form"]').serialize();
			$.post('../php/g_add.php',result,function(data){
				if(data=="exit"){
					alert('添加成功');
					location.reload();
					};
				})
			});
	 });
	$('#select_g').click(function(){
			$('[name="g_form1"]').toggle();
			$('[name="g_form"]').hide();
			$('[name="g_form2"]').hide();
			$('[name="g_btn1"]').click(function(){
			var result=$('[name="g_form1"]').serialize();
			$.post('../php/g_sel.php',result,function(data){
					alert(data);
			});
		});
		});
	$('#add_s').click(function(){
			$('[name="s_form"]').toggle();
			$('[name="s_form1"]').hide();
			$('[name="s_form2"]').hide();
			$('[name="s_btn"]').click(function(){
			var result=$('[name="s_form"]').serialize();
			$.post('../php/s_add.php',result,function(data){
				if(data=="exit"){
					alert('添加成功');
					location.reload();
					};
				})
			});
	 });
	 $('#select_s').click(function(){
			$('[name="s_form1"]').toggle();
			$('[name="s_form"]').hide();
			$('[name="s_form2"]').hide();
			$('[name="s_btn1"]').click(function(){
			var result=$('[name="s_form1"]').serialize();
			$.post('../php/s_sel.php',result,function(data){
					alert(data);
			});
		});
		});
});
