SET NAMES UTF8;
DROP DATABASE IF EXISTS user;
CREATE DATABASE user CHARSET=UTF8;
USE user;
CREATE TABLE users(
	dno INT PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(32),
	pwd VARCHAR(32)
);
INSERT INTO users VALUES(null,'丁丁','123456');
INSERT INTO users VALUES(null,'当当','dd123456');